basePath: '{{.BasePath}}'
host: '{{.Host}}'
info:
  contact: {}
  description: '{{.Description}}'
  license: {}
  title: '{{.Title}}'
  version: '{{.Version}}'
paths:
  /user/test:
    get:
      description: Add a new user
      responses:
        "200": {}
      summary: Add new user to the database
      tags:
      - user
swagger: "2.0"
